---
title: "figure_1"
author: "Donny Williams"
date: "11/9/2020"
output: html_document
---

# Packages
```{r}
# packages
library(GGMncv)
library(ggplot2)
library(cowplot)
```


# SCAD
```{r}
# SCAD
thetas <- seq(-5, 5, length.out = 10000)

# gammas
gamma <- c(2, 3.7, 5, 10)

# penalty
scad <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  pen <-  GGMncv:::scad_pen(Theta = abs(thetas), 
                                            lambda = 1, 
                                            gamma = gamma[x])
                  data.frame(
                    type = "SCAD",
                    pen = pen,
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = thetas
                  )
                }))

# lasso
lasso <- data.frame(type = "SCAD", 
                    pen = abs(thetas), 
                    gamma = 10000, 
                    which_one = "penalty",  
                    thetas = thetas)

# best subset
l0 <-  GGMncv:::atan_pen(Theta = abs(thetas), 
                         lambda = 1, 
                         gamma = 0.0001)

l0_dat <- data.frame(type = "SCAD", 
                     pen = l0, 
                     gamma = 0, 
                     which_one = "penalty",  
                     thetas = thetas)


dat <- rbind.data.frame(scad, lasso, l0_dat)


# penalty plot
scad_pen <- ggplot(dat, aes(
  x = thetas,
  y = pen,
  color = as.factor(gamma)
)) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p)[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 2"),
      expression(gamma ~ "= 3.7"),
      expression(gamma ~ "= 5"),
      expression(gamma ~ "= 10"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 5.001)) +
  scale_x_continuous(limits = c(-5.001, 5.001)) +
  guides(color = FALSE)



# derivative
scad <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  pen <-
                    GGMncv:::scad_deriv(abs(thetas), lambda = 1, gamma = gamma[x])
                  data.frame(
                    type = "SCAD",
                    pen = pen,
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = abs(thetas)
                  )
                }))

lasso <- data.frame(
  type = "SCAD",
  pen = 1,
  gamma = 10000,
  which_one = "penalty",
  thetas = abs(thetas)
)

l0 <-  GGMncv:::atan_deriv(Theta = abs(thetas), 
                           lambda = 1, 
                           gamma = 0.0001)

l0_dat <- data.frame(
  type = "SCAD",
  pen = abs(l0) * 1000,
  gamma = 0,
  which_one = "penalty",
  thetas = abs(thetas) * 10000
)


dat <- rbind.data.frame(scad, lasso, l0_dat)

scad_deriv <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   0,
    x = 0,
    xend = 2,
    color = "#000000",
    size = 1
  ) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p * "'")[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 2"),
      expression(gamma ~ "= 3.7"),
      expression(gamma ~ "= 5"),
      expression(gamma ~ "= 10"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    legend.title = element_blank(),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 1.01)) +
  scale_x_continuous(limits = c(-0.001, 5)) 


# SCAD plots
one <- cowplot::plot_grid(
  scad_pen,
  NULL,
  scad_deriv + guides(color = FALSE),
  cowplot::get_legend(scad_deriv),
  nrow = 1,
  rel_widths = c(1, .20, 1, 0.25)
)
```


# MCP
```{r}
## MCP
thetas <- seq(-5, 5, length.out = 10000)

# gammas
gamma <- c(2, 3.7, 5, 10)

mcp <- do.call(rbind.data.frame,
               lapply(1:4, function(x) {
                 pen <-  GGMncv:::mcp_pen(abs(thetas), lambda = 1, gamma = gamma[x])
                 data.frame(
                   type = "MCP",
                   pen = pen,
                   gamma = gamma[x],
                   which_one = "penalty",
                   thetas = thetas
                 )
               }))

lasso <- data.frame(
  type = "MCP",
  pen = abs(thetas),
  gamma = 10000,
  which_one = "penalty",
  thetas = thetas
)

l0 <-  GGMncv:::atan_pen(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "MCP",
  pen = l0,
  gamma = 0,
  which_one = "penalty",
  thetas = thetas
)


dat <- rbind.data.frame(mcp, lasso, l0_dat)

mcp_pen <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p)[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 2"),
      expression(gamma ~ "= 3.7"),
      expression(gamma ~ "= 5"),
      expression(gamma ~ "= 10"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 5.001)) +
  scale_x_continuous(limits = c(-5.001, 5.001)) +
  guides(color = FALSE)

mcp_pen



mcp <- do.call(rbind.data.frame,
               lapply(1:4, function(x) {
                 pen <-
                   GGMncv:::mcp_deriv(abs(thetas), lambda = 1, gamma = gamma[x])
                 data.frame(
                   type = "MCP",
                   pen = pen,
                   gamma = gamma[x],
                   which_one = "penalty",
                   thetas = abs(thetas)
                 )
               }))

lasso <- data.frame(
  type = "MCP",
  pen = 1,
  gamma = 10000,
  which_one = "penalty",
  thetas = abs(thetas)
)

l0 <-  GGMncv:::atan_deriv(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "MCP",
  pen = abs(l0) * 1000,
  gamma = 0,
  which_one = "penalty",
  thetas = abs(thetas) * 10000
)


dat <- rbind.data.frame(mcp, lasso, l0_dat)

mcp_deriv <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   0,
    x = 0,
    xend = 2,
    color = "#000000",
    size = 1
  ) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p * "'")[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 2"),
      expression(gamma ~ "= 3.7"),
      expression(gamma ~ "= 5"),
      expression(gamma ~ "= 10"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    legend.title = element_blank(),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 1.01)) +
  scale_x_continuous(limits = c(-0.001, 5))


two <- cowplot::plot_grid(
  mcp_pen,
  NULL,
  mcp_deriv + guides(color = FALSE),
  cowplot::get_legend(mcp_deriv),
  nrow = 1,
  rel_widths = c(1, .20, 1, 0.25)
)
```


# SELO
```{r}
## SELO
thetas <- seq(-5, 5, length.out = 10000)

# SELO
gamma <- c(0.01, 0.1, 0.5, 1)


# selo
selo <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  pen <-  GGMncv:::selo_pen(Theta = abs(thetas),
                                            lambda = 1,
                                            gamma = gamma[x])
                  data.frame(
                    type = "SELO",
                    pen = pen,
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = thetas
                  )
                }))

lasso <- data.frame(
  type = "SELO",
  pen = abs(thetas),
  gamma = 10000,
  which_one = "penalty",
  thetas = thetas
)

l0 <-  GGMncv:::atan_pen(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "SELO",
  pen = l0,
  gamma = 0,
  which_one = "penalty",
  thetas = thetas
)


dat <- rbind.data.frame(selo, lasso, l0_dat)

selo_pen <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p)[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 0.01"),
      expression(gamma ~ "= 0.10"),
      expression(gamma ~ "= 0.50"),
      expression(gamma ~ "= 1"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 5.001)) +
  scale_x_continuous(limits = c(-5.001, 5.001)) +
  guides(color = FALSE)


Theta <- as.matrix(thetas)
p <- ncol(Theta)
Theta <- abs(Theta)


selo <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  Theta <- ifelse(Theta == 0, 1e-05, Theta)
                  pen <-
                    t(matrix(
                      numDeriv::grad(
                        GGMncv:::selo_pen,
                        x = Theta,
                        lambda = 1,
                        gamma = gamma[x]
                      ),
                      p,
                      10000
                    ))
                  
                  data.frame(
                    type = "SELO",
                    pen = as.matrix(pen),
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = thetas
                  )
                }))


lasso <- data.frame(
  type = "SELO",
  pen = 1,
  gamma = 10000,
  which_one = "penalty",
  thetas = abs(thetas)
)

l0 <-  GGMncv:::atan_deriv(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "SELO",
  pen = abs(l0) * 1000,
  gamma = 0,
  which_one = "penalty",
  thetas = abs(thetas) * 10000
)


dat <- rbind.data.frame(selo, lasso, l0_dat)

selo_deriv <- ggplot(dat, aes(
  x = thetas,
  y = pen,
  color = as.factor(gamma)
)) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   0,
    x = 0,
    xend = 2,
    color = "#000000",
    size = 1
  ) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid( ~ type) +
  ylab(expression(italic(p * "'")[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 0.01"),
      expression(gamma ~ "= 0.1"),
      expression(gamma ~ "= 0.5"),
      expression(gamma ~ "= 1"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    legend.title = element_blank(),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 1.01)) +
  scale_x_continuous(limits = c(-0.001, 5))

three <- cowplot::plot_grid(
  selo_pen,
  NULL,
  selo_deriv + guides(color = FALSE),
  cowplot::get_legend(selo_deriv),
  nrow = 1,
  rel_widths = c(1, .20, 1, 0.25)
)

```


# ATAN
```{r}
# ATAN
thetas <- seq(-5, 5, length.out = 10000)

# gammas
gamma <- c(0.01, 0.1, 0.5, 1)


# atan
atan <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  pen <-  GGMncv:::atan_pen(abs(thetas), lambda = 1, gamma = gamma[x])
                  data.frame(
                    type = "ATAN",
                    pen = pen,
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = thetas
                  )
                }))

lasso <- data.frame(
  type = "ATAN",
  pen = abs(thetas),
  gamma = 10000,
  which_one = "penalty",
  thetas = thetas
)

l0 <-  GGMncv:::atan_pen(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "ATAN",
  pen = l0,
  gamma = 0,
  which_one = "penalty",
  thetas = thetas
)


dat <- rbind.data.frame(atan, lasso, l0_dat)

atan_pen <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid(~ type) +
  ylab(expression(italic(p)[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 0.01"),
      expression(gamma ~ "= 0.10"),
      expression(gamma ~ "= 0.50"),
      expression(gamma ~ "= 1"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 5.001)) +
  scale_x_continuous(limits = c(-5.001, 5.001)) +
  guides(color = FALSE)


Theta <- as.matrix(thetas)
p <- ncol(Theta)
Theta <- abs(Theta)


atan <- do.call(rbind.data.frame,
                lapply(1:4, function(x) {
                  Theta <- ifelse(Theta == 0, 1e-05, Theta)
                  pen <-
                    GGMncv:::atan_deriv(Theta, lambda = 1, gamma[x])
                  
                  data.frame(
                    type = "ATAN",
                    pen = as.matrix(pen),
                    gamma = gamma[x],
                    which_one = "penalty",
                    thetas = thetas
                  )
                }))


lasso <- data.frame(
  type = "ATAN",
  pen = 1,
  gamma = 10000,
  which_one = "penalty",
  thetas = abs(thetas)
)

l0 <-  GGMncv:::atan_deriv(abs(thetas), lambda = 1, gamma = 0.0001)

l0_dat <- data.frame(
  type = "ATAN",
  pen = abs(l0) * 1000,
  gamma = 0,
  which_one = "penalty",
  thetas = abs(thetas) * 10000
)


dat <- rbind.data.frame(atan, lasso, l0_dat)

atan_deriv <-
  ggplot(dat, aes(
    x = thetas,
    y = pen,
    color = as.factor(gamma)
  )) +
  geom_line(size = 1) +
  annotate(
    "segment",
    y =  0,
    yend =   0,
    x = 0,
    xend = 2,
    color = "#000000",
    size = 1
  ) +
  annotate(
    "segment",
    y =  0,
    yend =   1,
    x = 0,
    xend = 0,
    color = "#000000",
    size = 1
  ) +
  facet_grid(~ type) +
  ylab(expression(italic(p * "'")[lambda][gamma] ~ "(" * theta * ")")) +
  xlab(expression(theta)) +
  scale_color_manual(
    name = "",
    values =  c(
      "#000000",
      "#D55E00",
      "#56B4E9",
      "#009E73",
      "#0072B2",
      "#CC79A7"
    ),
    labels = c(
      expression(italic(L)[0]),
      expression(gamma ~ "= 0.01"),
      expression(gamma ~ "= 0.1"),
      expression(gamma ~ "= 0.5"),
      expression(gamma ~ "= 1"),
      expression(italic(L)[1])
    )
  ) +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text.x = element_text(size = 10),
    legend.title = element_blank(),
    axis.title  = element_text(size = 12),
    legend.text.align = 0
  ) +
  scale_y_continuous(limits = c(0, 1.01)) +
  scale_x_continuous(limits = c(-0.001, 5))



four <- cowplot::plot_grid(
  atan_pen,
  NULL,
  atan_deriv + guides(color = FALSE),
  cowplot::get_legend(atan_deriv),
  nrow = 1,
  rel_widths = c(1, .2, 1, 0.25)
)
```

# Combine Plots
```{r}
figure_1 <- cowplot::plot_grid(one, 
                   two, 
                   three, 
                   four, 
                   nrow = 4, 
                   rel_heights = c(1,1,1,1))

# save (note pdf in paper)
ggsave(filename = "figure_1.jpg", 
       width = 9, 
       height = 10.5, dpi = 1200)
```